# This is a basic workflow to help you get started with Actions

name: Send Reactions Tweets

# Controls when the workflow will run
on:
  schedule: # “At 18:00 on Wednesday.”
    - cron: "0 18 * * 3" # "*/5 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run article reactions job
        uses: Satak/webrequest-action@v1.2.3
        with:
          # Web request URL endpoint
          url: "https://tma.theanshuman.dev/api/create-tweet-for/reactions"
          method: POST
          headers: '{"api-key": "${{ secrets.API_KEY }}"}'
