# This is a basic workflow to help you get started with Actions

name: Send Reactions Tweets

# Controls when the workflow will run
on:
  schedule:
    - cron: "*/10 * * * *" # "0 17 * * 1-4"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run article views job
        uses: Satak/webrequest-action@v1.2.3
        with:
          # Web request URL endpoint
          url: "https://tma.theanshuman.dev/api/create-tweet-for/views"
                    method: POST
          headers: '{"api-key": "${{ env.API_KEY }}"}'
